interface Window {
    syncSettingsDebugVisibility?: () => void;
    // Values originate in the JSON manifest; consumers retain their String()
    // conversion until the explicit bootstrap validates external metadata.
    __PT_APP_MANIFEST__?: {
        version?: unknown;
        releaseUrl?: unknown;
        downloadUrl?: unknown;
    };
    __PT_ASSET_VERSION__?: string;
}

interface LegacyAppState {
    // Legacy startup currently assigns the persisted string without validation.
    mode: PianoTrainerDomain.PracticeMode | (string & {});
    followAdvanceInfo: PianoTrainerDomain.FollowAdvanceInfo | null;
    currentExpectedContext: PianoTrainerDomain.ExpectedContext | null;
    earlyGraceReservations: Map<number, PianoTrainerDomain.EarlyGraceReservation>;
    isPlaying: boolean;
    isAudioBusy: boolean;
    zoom: number;
    baseBpm: number;
    speedPercent: number;
    looper: { enabled: boolean; min: number; max: number; };
    hands: { left: number | null; right: number | null; };
    practice: PianoTrainerDomain.HandSelection;
    playback: PianoTrainerDomain.HandSelection;
    modeSettings: Record<PianoTrainerDomain.PracticeMode, PianoTrainerDomain.ModeSettings>;
    audioEnabled: PianoTrainerDomain.AudioRouting;
    midiOutEnabled: PianoTrainerDomain.AudioRouting;
    midiOutVolume: number;
    midiInBoost: number;
    expectedNotes: PianoTrainerDomain.ExpectedNote[];
    pressedKeys: Set<number>;
    heldCorrectNotes: Map<number, number | null>;
    preExpectedHeldNotes: Set<number>;
    activeHeldIncorrectFeedback: Map<number, PianoTrainerDomain.FeedbackMarker>;
    releasedIncorrectFeedback: PianoTrainerDomain.FeedbackMarker[];
    correctFeedbackHistory: PianoTrainerDomain.FeedbackMarker[];
    realtimeWrongPressInCurrentContext: boolean;
    pendingAudio: PianoTrainerDomain.PendingPlaybackNote[];
    feedbackEnabled: boolean;
    anchorTime: PianoTrainerDomain.AudioTimeSeconds;
    score: { correct: number; wrong: number; };
    sustainedVisuals: PianoTrainerDomain.SustainedVisual[];
    visualNotesToStart: PianoTrainerDomain.PendingVisual[];
    activeTimeouts: number[];
    hardwareLEDState: Map<number, string>;
    recentMidiEchoes: PianoTrainerDomain.MidiEcho[];
    debugPersistentAnchors: boolean;
    debugEventFlow: boolean;
    debugMatchLogs: boolean;
    debugAnchorResolution: boolean;
    debugStickyFrameLimit: number;
    debugFrameSeq: number;
    debugAnchorHistory: PianoTrainerDomain.DebugFrame[];
    futurePreviewEnabled: boolean;
    futurePreviewDepth: number;
    correctHighlightEnabled: boolean;
    wledDdpDebugEnabled: boolean;
    helperVersion: string;
    updateManifestUrl: string;
    updateStatus: string;
    updateLastCheckedAt: number;
    updateInfo: {
        currentVersion: string;
        remoteVersion: string;
        updateAvailable: boolean;
        releaseUrl: string;
        downloadUrl: string;
    } | null;
    countInActive: boolean;
    lastLedPreviewEvents: PianoTrainerDomain.PreviewEvent[];
    ledPreviewTimeline: PianoTrainerDomain.PreviewTimelineEvent[];
    ledPreviewTimelineDirty: boolean;
    ledPreviewTraversalIndex: number;
    playerPianoType: number;
    playerRange: PianoTrainerDomain.PlayerRange | null;
    outOfRangeCurrentNotes: PianoTrainerDomain.OutOfRangeNote[];
    ledOutputMode: 'none' | 'midi' | 'wled';
    midiInChannel: PianoTrainerDomain.MidiInputChannel;
    midiOutChannel: PianoTrainerDomain.MidiChannel;
    midiLightsChannel: PianoTrainerDomain.MidiChannel;
    midiLedLowVelocity: boolean;
    ledReverse: boolean;
    wledIp: string;
    wledTransport: 'http-json' | 'ddp';
    wledActiveTransport: 'http-json' | 'ddp';
    wledHelperAvailable: boolean;
    wledHelperStatus: string;
    wledStatus: string;
    wledConnectionState: 'none' | 'disconnected' | 'connected';
    ledCalibrationMode: boolean;
    ledCalibrationSelectedMidi: number | null;
    visualPulseEnabled: boolean;
    accentedDownbeatEnabled: boolean;
    loopCountInEnabled: boolean;
    metronomeMidiOutEnabled: boolean;
    currentScoreData: PianoTrainerDomain.ScoreRawData | null;
    currentScoreOriginalData: PianoTrainerDomain.ScoreRawData | null;
    currentScoreFileName: string;
    currentScoreOriginalFileName: string;
    inputVelocityEnabled: boolean;
    liveLowLatencyMonitoringEnabled: boolean;
    lowLatencyPlaybackEnabled: boolean;
    currentScoreFileType: string;
    currentScoreOriginalFileType: string;
    currentScoreLibraryId: string | null;
    currentScoreTitle: string;
    fullscreenOnPlay: boolean;
    pseudoFullscreenActive: boolean;
    transpose: {
        available: boolean;
        sourceKeyLabel: string;
        sourceKeyFound: boolean;
        mode: 'key' | 'semitone';
        semitones: number;
        targetKey: string | null;
        updateKeySignature: boolean;
        active: boolean;
        activeLabel: string;
        disableReason: string;
    };
    scoreLibrarySelectedFolderId: string | null;
    scoreLibraryView: 'folders' | 'scores';
    scoreLibraryManageMode: boolean;
    scoreLibrarySelectedScoreIds: string[];
    // These five fields are dynamically added by legacy LED / library UI.
    wledDdpLastSendOk?: boolean;
    wledDdpLastSendAt?: number;
    wledDdpLastError?: string;
    scoreLibrarySelectedFolderIds?: string[];
    scoreLibraryFolderManageMode?: boolean;
}
