const assert=require('node:assert/strict'),{test}=require('node:test');
const {harness,Select}=require('../helpers/device-controls-harness.cjs');
const plain=value=>JSON.parse(JSON.stringify(value));const response=version=>({ok:true,json:async()=>({version})});
test('range factory is cold; persisted init/filtering preserves Map identity and optional output order',()=>{
 const h=harness(),map=h.state.heldCorrectNotes;assert.deepEqual(h.effects,[]);h.storage.setItem('range','25');h.range.init();h.range.init();assert.equal(h.nodes.get('select-player-piano-type').listeners.length,1);assert.equal(h.state.playerPianoType,25);assert.equal(h.state.heldCorrectNotes,map);assert.deepEqual([...map],[[60,2]]);assert.deepEqual(plain(h.state.expectedNotes),[{midi:60}]);assert.deepEqual(plain(h.state.outOfRangeCurrentNotes),[{midi:15}]);assert.equal(h.nodes.get('player-piano-range-label').textContent,'Playable Range: MIDI 52–76');assert.deepEqual(h.effects.map(x=>x[0]),['mapping','invalidate','outputs','mapping','invalidate','outputs']);assert.equal(h.state.ledPreviewTimelineDirty,true);assert.equal(h.state.ledPreviewTraversalIndex,-1);assert.equal(h.state.lastLedPreviewEvents.length,0);
});
test('range native target validation, ordinary set options and explicit listener disposal/fresh lifetime',()=>{
 const h=harness();h.range.init();h.effects.length=0;const select=h.nodes.get('select-player-piano-type'),old=select.listeners[0].handler;select.value='49';select.dispatch(h.event('change'));assert.equal(h.storage.getItem('range'),'49');assert.deepEqual(h.effects.map(x=>x[0]),['save-range','mapping','invalidate','outputs','keyboard']);h.effects.length=0;select.dispatch(h.event('change'),{});assert.deepEqual(h.effects,[]);
 h.range.dispose();h.range.dispose();assert.equal(select.listeners.length,0);assert.equal(select.dataset.boundPlayerRange,undefined);h.range.init();h.effects.length=0;old({target:select});assert.deepEqual(h.effects,[]);h.range.setPlayerPianoType('61',{save:false,rerender:false});assert.equal(h.state.playerPianoType,61);assert.equal(h.effects.some(x=>x[0]==='keyboard'||x[0]==='save-range'),false);
});
test('connection presentation keeps native port state, label fallback and no-op LED observations',()=>{
 const h=harness();h.nodes.get('midi-in').value='device';h.nodes.get('midi-out').value='missing';h.connection.refreshConnectionStatuses();assert.equal(h.nodes.get('midi-in-connection-status').label.textContent,'Connected');assert.equal(h.nodes.get('midi-out-connection-status').label.textContent,'Disconnected');assert.equal(h.nodes.get('led-connection-status').label.textContent,'None');assert.deepEqual(h.effects.map(x=>x[0]),['channel-ui','wled-ui']);
 h.state.ledOutputMode='wled';h.state.wledIp=' ';h.connection.updateConnectionStatuses();assert.equal(h.nodes.get('led-connection-status').label.textContent,'None');h.state.wledIp='device';h.state.wledConnectionState='connected';h.connection.updateConnectionStatuses();assert.equal(h.nodes.get('led-connection-status').label.textContent,'Connected');h.connection.updateConnectionStatusIndicator('led-connection-status','other','');assert.equal(h.nodes.get('led-connection-status').label.textContent,'None');
});
test('repeated update UI init preserves ordinary saved-state/automatic checks while deduplicating its button',async()=>{
 const h=harness();assert.equal(h.requests.length,0);h.ui.init();h.ui.init();assert.equal(h.nodes.get('btn-check-updates').listeners.length,1);assert.equal(h.requests.length,2);assert.equal(h.controllers.some(x=>x.signal.aborted),false);assert.equal(h.nodes.get('btn-check-updates').disabled,true);assert.equal(h.requests[0].url,'/manifest.json?t=1234567890');h.pending[1].resolve(response('2.0.0'));await new Promise(setImmediate);h.pending[0].resolve(response('1.0.0'));await new Promise(setImmediate);assert.equal(h.state.updateInfo.remoteVersion,'1.0.0');assert.equal(h.nodes.get('btn-check-updates').textContent,'Up to Date');assert.equal(h.nodes.get('btn-check-updates').disabled,false);h.ui.dispose();h.update.dispose();assert.equal(h.controllers.some(x=>x.signal.aborted),false);
});
test('update disposal aborts only its pending requests and old fetch completion cannot change fresh UI/state/navigation',async()=>{
 const h=harness();const external=new AbortController(),first=h.update.checkForUpdates(),second=h.update.checkForUpdates({manual:true});h.update.dispose();h.update.dispose();assert.ok(h.controllers.every(x=>x.signal.aborted));assert.equal(external.signal.aborted,false);const fresh=h.update.checkForUpdates({manual:true});h.pending[0].resolve({get ok(){throw Error('old response read');}});h.pending[1].reject(Error('aborted'));await Promise.all([first,second]);assert.equal(h.state.updateInfo,null);assert.equal(h.state.updateLastCheckedAt,0);assert.equal(h.nodes.get('btn-check-updates').disabled,true);assert.deepEqual(h.effects,[]);h.pending[2].resolve(response('99'));await fresh;assert.equal(h.state.updateInfo.remoteVersion,'99');assert.equal(h.nodes.get('btn-check-updates').disabled,false);
});
test('update disposal during pending JSON prevents auto-reload and does not run old finally UI sync',async()=>{
 const h=harness();h.location.hostname='example.test';let finishJson;const task=h.update.checkForUpdates();h.pending[0].resolve({ok:true,json:()=>new Promise(resolve=>{finishJson=resolve;})});await new Promise(setImmediate);assert.equal(typeof finishJson,'function');h.update.dispose();h.state.updateStatus='fresh status';finishJson({version:'999'});await task;assert.equal(h.state.updateStatus,'fresh status');assert.equal(h.state.updateInfo,null);assert.equal(h.nodes.get('btn-check-updates').disabled,true);assert.deepEqual(h.effects,[]);
});
test('update button preserves local download vs remote confirmation and only explicit disposal invalidates captured handlers',async()=>{
 const h=harness();h.state.updateManifestUrl='';h.updatePorts.manifestUrl='';h.ui.init();h.state.updateInfo={updateAvailable:true,remoteVersion:'99',downloadUrl:'https://example.test/download',releaseUrl:''};const button=h.nodes.get('btn-check-updates');button.dispatch(h.event('click'));assert.deepEqual(h.effects.at(-1),['open','https://example.test/download','_blank','noopener']);h.location.hostname='example.test';h.uiPorts.confirm=()=>false;button.dispatch(h.event('click'));assert.equal(h.effects.filter(x=>x[0]==='replace').length,0);h.uiPorts.confirm=()=>true;button.dispatch(h.event('click'));assert.ok(h.effects.at(-1)[1].includes('appv=99'));
 const old=button.listeners[0].handler;h.ui.dispose();h.ui.dispose();assert.equal(button.listeners.length,0);assert.equal(button.dataset.boundCheckUpdates,undefined);h.ui.init();h.effects.length=0;await old();assert.deepEqual(h.effects,[]);h.ui.dispose();
});
test('update URL cleanup, malformed version/error/coercion and unconfigured requests retain original state',async()=>{
 const h=harness();h.location.href='http://127.0.0.1:8081/index.html?appv=1.2.3&t=4&led=off#score';h.storage.setItem('override','9');h.update.clearAssetVersionOverrideIfCurrent();assert.equal(h.storage.getItem('override'),null);assert.deepEqual(h.effects.at(-1),['history','/index.html?led=off#score']);const task=h.update.checkForUpdates({manual:true});h.pending[0].resolve({ok:false,status:404});await task;assert.equal(h.state.updateStatus,'Update check failed: Manifest HTTP 404');h.state.updateManifestUrl='';await h.update.checkForUpdates();assert.equal(h.controllers.length,1);assert.equal(h.state.updateStatus,'Update checks are not configured yet.');
});
